# Generated by Django 5.0.4 on 2024-04-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='district',
            new_name='aadhaar_no',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pin_code',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='police_station_code',
            new_name='police_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='police_station_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='taluka',
        ),
        migrations.RemoveField(
            model_name='user',
            name='thane_incharge',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='contact_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
