# Generated by Django 5.0.3 on 2024-04-07 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stolenlaptopdetails',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stolen_laptop_details', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
