# Generated by Django 5.0.3 on 2024-04-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_stolenlaptopdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stolenlaptopdetails',
            name='approximate_time',
            field=models.TimeField(null=True),
        ),
    ]
