# Generated by Django 5.0.3 on 2024-04-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
