# Generated by Django 5.0.3 on 2024-04-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_stolenlaptopdetails_approximate_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stolenlaptopdetails',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
