# Generated by Django 5.0.3 on 2024-04-23 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_stolenlaptopdetails_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
