# Generated by Django 4.2.11 on 2024-04-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
