# Generated by Django 5.0.4 on 2024-04-27 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_pcapfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcapfile',
            old_name='filename',
            new_name='name',
        ),
    ]
