# Generated by Django 5.0.4 on 2024-04-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_rename_filename_pcapfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcapfile',
            name='file',
            field=models.FileField(upload_to='pcap_files'),
        ),
    ]
