# Generated by Django 5.0.4 on 2024-04-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_alter_pcapfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcapfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
